#!/usr/bin/env python3
"""Copy and verify a self-contained paper, numerical sources, and audit scripts.

The destination must be new. Source files are read twice to reject a snapshot
that changes during copying. Compilation products are regenerated by build_all.sh.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
STEMS = ('fm4pde_jmlr_revision_0906',
         'fm4pde_jmlr_revision_scoped_reviewer_map_0906',
         'supplement', 'response_to_reviewers_scoped_0906')
DIRECTORIES = ('source_data', 'figures', 'audit', 'review')
TRANSIENT_SUFFIXES = ('.aux', '.blg', '.fdb_latexmk', '.fls', '.out',
                      '.synctex.gz', '.xdv', '.pyc', '.pyo')


def sha(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def files(root):
    selected = []
    for path in sorted(root.rglob('*')):
        relative = path.relative_to(root)
        if any(part in ('.git', '__pycache__') for part in relative.parts):
            continue
        if not path.is_file() or str(path).endswith(TRANSIENT_SUFFIXES):
            continue
        if len(relative.parts) == 1:
            if path.suffix not in ('.tex', '.bib', '.bst', '.sty', '.cls', '.sh', '.md', '.csv'):
                if path.name not in {stem + '.pdf' for stem in STEMS}:
                    continue
        elif relative.parts[0] not in DIRECTORIES:
            continue
        selected.append(path)
    return selected


def verify(destination):
    manifest = json.loads((destination / 'PAPER_ASSETS_MANIFEST.json').read_text())
    for record in manifest['files']:
        path = destination / record['path']
        assert not path.is_symlink(), path
        assert path.stat().st_size == record['bytes'], path
        assert sha(path) == record['sha256'], path
        assert bool(path.stat().st_mode & 0o111) == record['executable'], path
    qa = json.loads((destination / 'audit/revision_0909/current_revision_qa.json').read_text())
    for stem in STEMS:
        assert qa['pdfs'][stem]['tex_sha256'] == sha(destination / (stem + '.tex')), stem
        assert qa['pdfs'][stem]['pdf_sha256'] == sha(destination / (stem + '.pdf')), stem
    for relative, digest in qa['figure_hashes'].items():
        assert sha(destination / relative) == digest, relative
    if manifest['stage'] == 'final':
        assert qa.get('ns_main_and_timing_integrated') is True
        assert qa.get('conditional_scaling_integrated') is True
        assert qa.get('manuscript_complete') is True
        assert qa.get('pending_manuscript_work') == []
    return dict(status='pass', stage=manifest['stage'], files=len(manifest['files']),
                bytes=sum(item['bytes'] for item in manifest['files']),
                manifest_sha256=sha(destination / 'PAPER_ASSETS_MANIFEST.json'))


def capture(source, destination, stage):
    if destination.exists():
        raise FileExistsError(f'Use a new destination: {destination}')
    if source == destination or source in destination.parents:
        raise ValueError('The destination must be outside the source paper')
    qa_path = source / 'audit/revision_0909/current_revision_qa.json'
    qa = json.loads(qa_path.read_text())
    for stem in STEMS:
        assert qa['pdfs'][stem]['tex_sha256'] == sha(source / (stem + '.tex')), stem
        assert qa['pdfs'][stem]['pdf_sha256'] == sha(source / (stem + '.pdf')), stem
    if stage == 'final':
        assert qa.get('ns_main_and_timing_integrated') is True
        assert qa.get('conditional_scaling_integrated') is True
        assert qa.get('manuscript_complete') is True
        assert qa.get('pending_manuscript_work') == []
    destination.parent.mkdir(parents=True, exist_ok=True)
    selected = files(source)
    records = []
    with tempfile.TemporaryDirectory(dir=destination.parent, prefix='.paper-assets-') as temp:
        staging = Path(temp) / 'paper'
        staging.mkdir()
        for src in selected:
            relative = src.relative_to(source)
            before = sha(src)
            dst = staging / relative
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst, follow_symlinks=True)
            assert sha(dst) == before == sha(src), f'Changing source: {src}'
            records.append(dict(path=str(relative), bytes=dst.stat().st_size,
                                sha256=before, executable=bool(src.stat().st_mode & 0o111)))
        # Check all selected files once more after the copy, not only per-file.
        assert [p.relative_to(source) for p in files(source)] == [Path(r['path']) for r in records]
        for record in records:
            assert sha(source / record['path']) == record['sha256'], record['path']
        manifest = dict(schema_version=1, stage=stage, source=str(source),
                        source_git_head=subprocess.check_output(
                            ['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip(),
                        source_git_status=subprocess.check_output(
                            ['git', '-C', str(source), 'status', '--porcelain'], text=True).splitlines(),
                        scope='Paper sources, four PDFs, all figures and numerical sources, '
                              'review inputs, and audit/analysis scripts; mixed main and ablation assets.',
                        current_qa_sha256=sha(qa_path), files=records)
        (staging / 'PAPER_ASSETS_MANIFEST.json').write_text(json.dumps(manifest, indent=2) + '\n')
        verify(staging)
        if destination.exists():
            raise FileExistsError(destination)
        os.rename(staging, destination)
    return verify(destination)


def restore(archive, destination):
    if destination.exists():
        raise FileExistsError(f'Restore requires a new destination: {destination}')
    if archive == destination or archive in destination.parents:
        raise ValueError('Restore must not write inside the immutable paper archive')
    original = verify(archive)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=destination.parent, prefix='.paper-restore-') as temp:
        staging = Path(temp) / 'paper'
        shutil.copytree(archive, staging)
        result = verify(staging)
        assert result['manifest_sha256'] == original['manifest_sha256']
        assert verify(archive) == original, 'Archive changed during restoration'
        if destination.exists():
            raise FileExistsError(destination)
        os.rename(staging, destination)
    result['destination'] = str(destination)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('mode', choices=('capture', 'verify', 'restore'))
    parser.add_argument('--paper', type=Path)
    parser.add_argument('--archive', type=Path, default=HERE / 'paper_assets')
    parser.add_argument('--destination', type=Path, default=HERE / 'paper_assets')
    parser.add_argument('--stage', choices=('working-draft', 'final'), default='final')
    args = parser.parse_args()
    if args.mode == 'capture':
        if args.paper is None:
            parser.error('capture requires --paper')
        result = capture(args.paper.resolve(), args.destination.resolve(), args.stage)
    elif args.mode == 'restore':
        result = restore(args.archive.resolve(), args.destination.resolve())
    else:
        result = verify(args.destination.resolve())
    print(json.dumps(result))


if __name__ == '__main__':
    main()
