data:
  name: 'helmholtz'
  datapath: '/large_storage/zhangxf/PDEdata/test1125/helmholtz_test_1000-128-128-k1.mat'
  # datapath: '/large_storage/zhangxf/PDEdata/helmholtz/helmholtz_1000-128-128_test.mat'
  remark: 'k1_test'
  # remark: 'k1_train'
  offset: 0
  img_channels: 2
  img_resolution: 128
  obs_size: 500
  coef: f_data
  solution: psi_data
  loadby: 'scipy'

model:
  pre-trained: '/research_data/users/zhangxifeng/C01Python/FM4PDE/output/pretrained/fm4helmholtz.pth'

generate:
  seed: 0
  device: 'cuda:1'
  batch_size: 1
  zeta_obs_a: 30000
  zeta_obs_u: 30000
  zeta_pde: 1
  num_steps: 1000
  step_size: 0.001
  method: 'euler'
  guide: True
  process: True
  scheduler: "CondOT"
  training: "velocity"
  full: False
  samplemode: "stochastic"
  # samplemode: "deterministic"
  stochastic_t: 1
  obsguide_t: 0.8
  obsguide_decay: 0.1

output:
  savepath: '/research_data/users/zhangxifeng/C01Python/Eval/DeepLearning4PDE/samples/FM4PDE/'
  save: True
  plot: True
  return: False
