data:
  name: 'poisson'
  datapath: '/large_storage/zhangxf/PDEdata/test1125/poisson_test_1000-128-128.mat'
  # datapath: '/large_storage/zhangxf/PDEdata/poisson/poisson_1000-128-128_test.mat'
  remark: 'test'
  # remark: 'train'
  offset: 100
  img_channels: 2
  img_resolution: 128
  obs_size: 500
  coef: f_data
  solution: phi_data
  loadby: 'scipy'

model:
  pre-trained: '/research_data/users/zhangxifeng/C01Python/FM4PDE/output/pretrained/fm4poisson.pth'

generate:
  seed: 42
  device: 'cuda:1'
  batch_size: 1
  zeta_obs_a: 60000
  zeta_obs_u: 5000000
  # zeta_obs_u: 500000000 inverse full
  zeta_pde: 1
  num_steps: 1000
  step_size: 0.001
  method: 'euler'
  guide: True
  process: True
  scheduler: "CondOT"
  training: "velocity"
  full: False
  samplemode: "stochastic"
  # samplemode: "deterministic"
  stochastic_t: 1
  obsguide_t: 1
  obsguide_decay: 1

output:
  savepath: '/research_data/users/zhangxifeng/C01Python/Eval/DeepLearning4PDE/samples/FM4PDE/'
  plot: True
  save: True
  return: False
  

